-- Run after all 20260910 migrations. Client records exist independently of login accounts.
begin;
create table public.client_records (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique references public.profiles(id) on delete restrict,
  full_name text not null check(length(trim(full_name)) between 1 and 120),
  phone text check(phone is null or phone ~ '^09[0-9]{9}$'),
  email text,
  birthdate date,
  created_at timestamptz not null default now(),
  created_by uuid,
  version integer not null default 1
);
alter table public.client_records enable row level security;
revoke all on public.client_records from public,anon,authenticated;
grant select on public.client_records to authenticated;
create policy client_record_read on public.client_records for select to authenticated
using(clinic_private.active_user() and (clinic_private.manager() or profile_id=auth.uid()));
alter table public.appointments add column client_record_id uuid references public.client_records(id) on delete restrict;
alter table public.appointments add column booking_source text not null default 'online' check(booking_source in ('online','walk_in','call','text'));
alter table public.appointments add column staff_request_id uuid unique;
create index appointments_client_record on public.appointments(client_record_id,appointment_date);

insert into public.client_records(profile_id,full_name,phone,email,birthdate,created_at)
select id,coalesce(nullif(trim(full_name),''),'Unnamed client'),case when phone ~ '^09[0-9]{9}$' then phone else null end,(select lower(email) from auth.users where id=profiles.id),birthdate,created_at
from public.profiles where role='client' or exists(select 1 from public.appointments where patient_id=profiles.id);
update public.appointments a set client_record_id=c.id from public.client_records c where c.profile_id=a.patient_id;
-- Names/phones alone do not prove identity. Historical walk-ins get separate records.
do $$ declare a public.appointments%rowtype; cid uuid; begin
  for a in select * from public.appointments where patient_id is null loop
    insert into public.client_records(full_name,phone,created_at) values(a.walk_in_name,a.walk_in_phone,a.created_at) returning id into cid;
    update public.appointments set client_record_id=cid,booking_source='walk_in' where id=a.id;
  end loop;
end $$;

create table clinic_private.client_invitations (
  client_id uuid primary key references public.client_records(id) on delete cascade,
  email text not null unique,
  token uuid not null unique default gen_random_uuid(),
  expires_at timestamptz not null default now()+interval '24 hours'
);
revoke all on clinic_private.client_invitations from public,anon,authenticated;

-- An invitation token is generated by staff on the server, never supplied as a role.
-- Matching email + unexpired token links the record during account creation atomically.
create or replace function clinic_private.create_client_profile_record() returns trigger
language plpgsql security definer set search_path='' as $$
declare invitation clinic_private.client_invitations%rowtype; metadata jsonb; account_email text;
begin
  perform pg_advisory_xact_lock(817260927);
  select raw_user_meta_data,email into metadata,account_email from auth.users where id=new.id;
  select * into invitation from clinic_private.client_invitations
    where token::text=metadata->>'clinic_invitation_token' and email=lower(account_email) and expires_at>now() for update;
  if found then
    perform 1 from public.client_records where id=invitation.client_id and profile_id is null for update;
    if not found then raise exception 'Client record already has an account.'; end if;
    update public.client_records set profile_id=new.id,email=lower(account_email),version=version+1 where id=invitation.client_id;
    update public.appointments set patient_id=new.id,walk_in_name=null,walk_in_phone=null,walk_in_request_id=null where client_record_id=invitation.client_id;
    update public.appointment_events e set patient_id=new.id from public.appointments a where e.appointment_id=a.id::text and a.client_record_id=invitation.client_id;
    delete from clinic_private.client_invitations where client_id=invitation.client_id;
  elsif new.role='client' then
    insert into public.client_records(profile_id,full_name,phone,email,birthdate)
    values(new.id,coalesce(nullif(trim(new.full_name),''),'Unnamed client'),case when new.phone ~ '^09[0-9]{9}$' then new.phone else null end,lower(account_email),new.birthdate);
  end if;
  return new;
end $$;
create trigger clinic_client_profile after insert on public.profiles for each row execute function clinic_private.create_client_profile_record();
revoke all on function clinic_private.create_client_profile_record() from public,anon,authenticated;

create or replace function clinic_private.attach_client_record() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  if new.client_record_id is null then
    if new.patient_id is not null then
      select id into new.client_record_id from public.client_records where profile_id=new.patient_id;
      if new.client_record_id is null then
        insert into public.client_records(profile_id,full_name,phone)
        select id,coalesce(nullif(trim(full_name),''),'Unnamed client'),case when phone ~ '^09[0-9]{9}$' then phone else null end from public.profiles where id=new.patient_id
        on conflict(profile_id) do update set profile_id=excluded.profile_id returning id into new.client_record_id;
      end if;
    else
      insert into public.client_records(full_name,phone) values(new.walk_in_name,new.walk_in_phone) returning id into new.client_record_id;
      new.booking_source:='walk_in';
    end if;
  end if;
  return new;
end $$;
create trigger clinic_attach_client before insert on public.appointments for each row execute function clinic_private.attach_client_record();
revoke all on function clinic_private.attach_client_record() from public,anon,authenticated;

create or replace function public.save_client_record(p_id uuid,p_version integer,p_name text,p_phone text,p_email text,p_birthdate date) returns uuid
language plpgsql security definer set search_path='' as $$
declare cid uuid; normalized_phone text;
begin
  if not clinic_private.manager() then raise exception 'Management access required.'; end if;
  if p_name is null or length(trim(p_name)) not between 1 and 120 then raise exception 'Enter the client full name (1 to 120 characters).'; end if;
  normalized_phone:=nullif(regexp_replace(coalesce(p_phone,''),'[[:space:]()-]','','g'),'');
  if normalized_phone ~ '^([+]63|63)9[0-9]{9}$' then normalized_phone:='0'||regexp_replace(normalized_phone,'^[+]?63',''); end if;
  if normalized_phone is not null and normalized_phone !~ '^09[0-9]{9}$' then raise exception 'Enter a valid Philippine mobile number.'; end if;
  if nullif(trim(p_email),'') is not null and (length(p_email)>254 or trim(p_email) !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$') then raise exception 'Enter a valid email address.'; end if;
  if p_birthdate>(now() at time zone 'Asia/Manila')::date then raise exception 'Birthdate cannot be in the future.'; end if;
  if p_version is null then
    insert into public.client_records(id,full_name,phone,email,birthdate,created_by) values(coalesce(p_id,gen_random_uuid()),trim(p_name),normalized_phone,lower(nullif(trim(p_email),'')),p_birthdate,auth.uid())
    on conflict(id) do nothing returning id into cid;
    if cid is null then
      select id into cid from public.client_records where id=p_id and full_name=trim(p_name) and phone is not distinct from normalized_phone and email is not distinct from lower(nullif(trim(p_email),'')) and birthdate is not distinct from p_birthdate;
      if cid is null then raise exception 'This record already exists with different details. Refresh and edit the saved record.'; end if;
    end if;
  else
    update public.client_records set full_name=trim(p_name),phone=normalized_phone,email=lower(nullif(trim(p_email),'')),birthdate=p_birthdate,version=version+1
    where id=p_id and version=p_version returning id into cid;
    if cid is null then raise exception 'This record changed. Refresh before editing again.'; end if;
  end if;
  return cid;
end $$;

-- Called by the authenticated staff's Edge Function client. Tokens never go to the UI.
create or replace function public.prepare_client_invitation(p_client_id uuid) returns jsonb
language plpgsql security definer set search_path='' as $$
declare c public.client_records%rowtype; invitation clinic_private.client_invitations%rowtype;
begin
  if not clinic_private.manager() then raise exception 'Management access required.'; end if;
  perform pg_advisory_xact_lock(817260927);
  select * into strict c from public.client_records where id=p_client_id for update;
  if c.profile_id is not null then raise exception 'This client already has a login. They can use Forgot password to set or recover it.'; end if;
  if c.email is null then raise exception 'Add the client email address first.'; end if;
  if exists(select 1 from auth.users where lower(email)=c.email) then raise exception 'This email already has an account. Use its existing client record; do not create another account.'; end if;
  insert into clinic_private.client_invitations(client_id,email) values(c.id,c.email)
  on conflict(client_id) do update set email=excluded.email,expires_at=now()+interval '24 hours' returning * into invitation;
  return jsonb_build_object('email',c.email,'name',c.full_name,'phone',c.phone,'token',invitation.token);
end $$;

create or replace function public.available_staff_slots(p_date date,p_service_ids uuid[],p_source text) returns table(appointment_date date,time_slot text)
language plpgsql security definer set search_path='' as $$
declare cfg public.clinic_settings%rowtype; duration integer; start_local timestamp; end_local timestamp; start_utc timestamptz; end_utc timestamptz;
begin
  if not clinic_private.manager() then raise exception 'Management access required.'; end if;
  if p_source is null or p_source not in ('walk_in','call','text') then raise exception 'Choose walk-in, call or text.'; end if;
  if coalesce(cardinality(p_service_ids),0)=0 or array_position(p_service_ids,null) is not null then raise exception 'Select services.'; end if;
  select sum(duration_minutes) into duration from public.services where id=any(p_service_ids) and is_active;
  if (select count(*) from public.services where id=any(p_service_ids) and is_active)<>cardinality(p_service_ids) then raise exception 'A service is unavailable or repeated.'; end if;
  select * into strict cfg from public.clinic_settings where id=1;
  if p_date is null or p_date<(now() at time zone 'Asia/Manila')::date or p_date>(now() at time zone 'Asia/Manila')::date+cfg.booking_horizon_days then return; end if;
  if p_source='walk_in' and p_date<>(now() at time zone 'Asia/Manila')::date then return; end if;
  if not(extract(dow from p_date)::integer=any(cfg.opening_days)) or exists(select 1 from public.clinic_closures where closure_date=p_date) then return; end if;
  for start_local in select generate_series(p_date+cfg.morning_start,p_date+cfg.afternoon_end,interval '15 minutes') loop
    end_local:=start_local+make_interval(mins=>duration);
    if not ((start_local::time>=cfg.morning_start and end_local<=p_date+cfg.morning_end) or (start_local::time>=cfg.afternoon_start and end_local<=p_date+cfg.afternoon_end)) then continue; end if;
    start_utc:=start_local at time zone 'Asia/Manila'; end_utc:=end_local at time zone 'Asia/Manila';
    if start_utc<=now() then continue; end if;
    if exists(select 1 from public.appointments a where (a.status in ('pending','confirmed','cancellation_requested') or (a.status='completed' and (a.completed_at is null or a.completed_at>=a.starts_at))) and a.starts_at<end_utc and a.ends_at>start_utc) then continue; end if;
    appointment_date:=p_date; time_slot:=to_char(start_local,'HH12:MI AM')||' - '||to_char(end_local,'HH12:MI AM'); return next;
  end loop;
end $$;

create or replace function public.book_staff_appointment(p_client_id uuid,p_service_ids uuid[],p_date date,p_time_slot text,p_source text,p_request_id uuid) returns text
language plpgsql security definer set search_path='' as $$
declare c public.client_records%rowtype; appt public.appointments%rowtype; duration integer; total numeric; names text; start_time timestamptz;
begin
  perform pg_advisory_xact_lock(817260902);
  if not clinic_private.manager() then raise exception 'Management access required.'; end if;
  if p_request_id is null then raise exception 'A request ID is required.'; end if;
  select * into appt from public.appointments where staff_request_id=p_request_id;
  if found then
    if appt.client_record_id is distinct from p_client_id or appt.service_ids is distinct from p_service_ids or appt.appointment_date is distinct from p_date or appt.time_slot is distinct from p_time_slot or appt.booking_source is distinct from p_source then raise exception 'This request was already used for another booking.'; end if;
    return appt.id::text;
  end if;
  select * into strict c from public.client_records where id=p_client_id for update;
  if c.profile_id is not null and not exists(select 1 from public.profiles where id=c.profile_id and is_active) then raise exception 'This client account is inactive.'; end if;
  perform id from public.services where id=any(p_service_ids) order by id for share;
  if not exists(select 1 from public.available_staff_slots(p_date,p_service_ids,p_source) s where s.time_slot=p_time_slot) then raise exception 'That time is no longer available. Select another.'; end if;
  select sum(s.duration_minutes),case when count(s.price)=count(*) then sum(s.price) else null end,string_agg(s.name,' + ' order by x.position)
  into duration,total,names from unnest(p_service_ids) with ordinality x(id,position) join public.services s on s.id=x.id;
  start_time:=clinic_private.slot_start(p_date,p_time_slot);
  insert into public.appointments(client_record_id,booking_source,staff_request_id,patient_id,walk_in_name,walk_in_phone,walk_in_request_id,service_id,service_ids,service_name,quoted_price,quote_is_estimate,duration_minutes,appointment_date,time_slot,status,starts_at,ends_at)
  values(c.id,p_source,p_request_id,c.profile_id,case when c.profile_id is null then c.full_name end,case when c.profile_id is null then c.phone end,case when c.profile_id is null then p_request_id end,case when cardinality(p_service_ids)=1 then p_service_ids[1] end,p_service_ids,names,total,total is null,duration,p_date,p_time_slot,'confirmed',start_time,start_time+make_interval(mins=>duration)) returning * into appt;
  insert into public.appointment_services(appointment_id,service_id,position,service_name,duration_minutes,quoted_price,quote_is_estimate)
  select appt.id,s.id,x.position::integer,s.name,s.duration_minutes,s.price,s.price is null from unnest(p_service_ids) with ordinality x(id,position) join public.services s on s.id=x.id;
  insert into public.appointment_events(appointment_id,patient_id,actor_id,action,note) values(appt.id::text,c.profile_id,auth.uid(),'staff_booked','Source: '||p_source||' · '||p_date::text||' · '||p_time_slot);
  return appt.id::text;
end $$;
revoke all on function public.save_client_record(uuid,integer,text,text,text,date),public.prepare_client_invitation(uuid),public.available_staff_slots(date,uuid[],text),public.book_staff_appointment(uuid,uuid[],date,text,text,uuid) from public,anon;
grant execute on function public.save_client_record(uuid,integer,text,text,text,date),public.prepare_client_invitation(uuid),public.available_staff_slots(date,uuid[],text),public.book_staff_appointment(uuid,uuid[],date,text,text,uuid) to authenticated;
notify pgrst,'reload schema';
commit;
